# Gmail SMTP
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: noreply.emergency.sevice@gmail.com
    password: <hereyourmailpassword>
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email:
  px:
    subject: Prescription Email
    template: email-template.ftl
    background-img: px_bg.png
    text: |
      <p>This prescription has been prepared specifically for your needs.</p>
      <p>Please use these medications as directed and follow the instructions provided by your doctor.</p>
      <p>Wishing you good health.</p>
