scheduler:
  cron:
    pattern:
      expired: "0 0 0/12 * * ?" #Every 12 hours (00:00 and 12:00), Every day
      applied: "0 10 0 * * ?" #Every 24 hours (00:10), Every day
  certain:
    time:
      before: 172800000