<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        .container {
            margin-top: 70px;
            display: block;
            width: 620px;
            height: 800px;
            position: relative;

            background-image: url("cid:backgroundImage");
            background-repeat: no-repeat;
            background-size: cover;
            font-family: Courier, monospace;
            color: #444444;
        }
        .blankA {
                 display: block;
                 width: 620px;
                 height: 80px;
                 position: relative;
        }
       .blankB {
                display: block;
                width: 620px;
                height: 95px;
                position: relative;
            }

        .header {
            font-size: 20px;
            font-weight: bold;
            color: blue;
            position: absolute;

            margin-left: 400px;
        }

        .content {
            margin-left: 100px;
            font-size: 16px;
            color: darkgray;
            position: absolute;
            top: 450px;
            left: 120px;
        }

        .content span {
            display: inline-block;
            width: 300px;
            margin-right: 10px;
        }

        .medicines {
            margin-left: 100px;
            font-size: 16px;
            color: darkgray;
            font-size: 14px;
            position: absolute;
            top: 250px;
            left: 120px;
        }

        .medicines ol {
            margin: 0;
            padding-left: 50px;
        }

        .footer {
            font-size: 12px;
            position: absolute;
            bottom: 20px;
            left: 20px;
        }
    </style>
</head>
<body>

<div class="container">
    <div class="blankA">

    </div>
    <div class="header">Dr. ${data.doctorLastName}, ${data.doctorFirstName}</div>
        <div class="blankB">

        </div>
    <div class="content">
        <span>${data.patientSSN}</span>${data.patientLastName}, ${data.patientFirstName}<br>
        <span>${data.patientAge}</span>${data.patientGender}<br>
        <span>${data.date}</span>${data.patientPhoneNum}<br>
        <div></span>${data.patientAddress}<div>
    </div>
    <div class="medicines">
        <ol>
            <#list data.medicines as medicine>
                <li>${medicine}</li>
            </#list>
        </ol>
    </div>
    <div class="footer">
        Generated by Adam BORN
    </div>
</div>
</body>
</html>
